#!/bin/bash
cd /tmp/rom
rm -rf .repo &

#wget https://github.com/phhusson/platform_frameworks_av/commit/624cfc90b8bedb024f289772960f3cd7072fa940.patch

source build/envsetup.sh
lunch du_r5x-userdebug

export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs -j16
	mka system-api-stubs-docs -j16
	mka test-api-stubs-docs -j16
}

make_rom(){
        make corvus -j16
	zip=$(up out/target/product/r5x/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom &
sleep 5200 && kill "$!"
