#!/bin/bash
cd /tmp/rom
rm -rf .repo &

cd /tmp/rom

source build/envsetup.sh


lunch aosp_r5x-userdebug
export SELINUX_IGNORE_NEVERALLOWS=true
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

# Telgram env setup
export BOT_MSG_URL="https://api.telegram.org/bot$API_BOT/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$API_BOT/sendDocument"

tg_post_msg() {
        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
        -d "parse_mode=html" \
        -d text="$1"
}

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	mka api-stubs-docs -j16
	mka system-api-stubs-docs -j16
	mka test-api-stubs-docs -j16
}

make_rom(){
	tg_post_msg "<b>Rom building CI Build Triggered for Realme 5x</b>" "$CHATID"
        mka bacon -j16

	if [ -f out/target/product/r5x/*zip ]; then
		zip=$(up out/target/product/r5x/*zip)
		echo " "
		echo "$zip"
		tg_post_msg "<b>Build Completed</b>%0A%0A<b>Link : </b> <code>"$zip"</code>" "$CHATID"
	else
		tg_post_msg "<b>OMG! Build Failed, check cirrus console and fix error</b>" "$CHATID"
	fi
}

make_metalava
make_rom
up
tg_post_msg &

sleep 5000 && kill "$!"
